import type { Metadata } from "next";
import '@/styles/globals.css'
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <body className="relative">
            {children}
            <Link
              href="/"
              className="fixed top-5 left-5 w-14 h-14 bg-slate-600 rounded-xl flex items-center justify-center text-white text-xl shadow-lg transition-colors duration-300 hover:bg-green-600"
              title="Voltar para a página inicial"
            >
              &#8592; 
            </Link>
          </body>
        </html>
      );
}
